---

services:
  mail:
    image: rnwood/smtp4dev:v3
    ports:
        - "1080:80"
  gitlab:
    image: gitlab/gitlab-ce:18.6.2-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.gitlab.orb.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.gitlab.orb.local'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail'
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = 'mta'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './run/config:/etc/gitlab'
      - './run/logs:/var/log/gitlab'
      - './run/data:/var/opt/gitlab'
    shm_size: '256m'
